# Generated by Django 3.2.8 on 2021-10-26 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rename_notification_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='link',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='creator',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
